Overhaul 4: The README's Last Hurrah
QuestCraftPlusPlus/QuestCraft pull request #546
Opened 2023-08-14 03:03 UTC by swaggio7

- Added LTS notes
- Added ModernFix and ServerCore, as per devmods.json
- Strikethroughed Vulkan, awaiting confirmation on whether or not it's coming to QC
- Reworked Mod-related crash solutions
- Added a strong warning NOT to enable Seated Mode
- Added README contributors
- Fixed many grammatical errors

Comments and edits are welcomed.

2023-08-14 03:10 UTC, Flopgop requested changes
Misc grammar changes.

2023-08-14 03:10 UTC, Flopgop commented on README.md
> +Next, open your headset's QuestCraft launcher (through Unknown Sources). Be sure to grant all requested permissions (Microphone perms are for Simple Voice Chat!). Once you're done, you'll follow the
Should probably use the full word here instead of just "perms"

2023-08-14 03:10 UTC, Flopgop commented on README.md
> +**NOTE: You may encounter crashes when downloading your selected MC version, ESPECIALLY on v53 and later. This is because Meta can't fix memory leaks, for some reason. Don't fret; launch the app agai
"left of" instead of "left off"

2023-08-14 03:10 UTC, Flopgop commented on README.md
> +QuestCraft, utilizing Vivecraft and Pojlib, is a standalone port of Minecraft: Java Edition to Oculus Quest Headsets. With a team of four main developers and 8 third-party developers, over the past y
"to run" instead of "to run on"

2023-08-14 03:16 UTC, Flopgop approved these changes
problems solved 👍

2023-08-14 03:16 UTC, DED0026 commented
ded approves :trollface:

2023-08-14 09:36 UTC, TecEash1 commented
Techy approves :trollface:

2023-08-14 22:16 UTC, swaggio7 commented
I have an idea! May take some time to complete it, though

2023-08-15 09:52 UTC, TecEash1 commented on README.md
> +Made with [contrib.rocks](https://contrib.rocks).
btw u may want to remove this

2023-08-15 09:59 UTC, TecEash1 requested changes

2023-08-15 09:59 UTC, TecEash1 commented on README.md
> +Made with [contrib.rocks](https://contrib.rocks).
btw u may want to remove this line

``Made with [contrib.rocks](https://contrib.rocks).``

2023-08-15 12:10 UTC, swaggio7 commented
> I have an idea! May take some time to complete it, though



Nevermind.

2023-08-15 17:47 UTC, TecEash1 approved these changes

2023-12-29 19:48 UTC, KendrickLamar2003 commented
Welp, I need to make another PR.

2023-12-29 19:48 UTC, closed without merging